### ISSUE TITLE
Test run gives pysam error

### ISSUE THREAD

**Issue by andosl** [oscarlr/IGenotyper#10]
(IGv2) msgroup@the-pirate:~/IGv2/test$ IG phase subset_bam/reads.bam test # There will be an warning message about no reads for hap0.bw -- you can ignore this
-----------------
Checking test/tmp/ccs.fasta
	Running command... 
bam2fasta -o test/tmp/ccs.fasta subset_bam/reads.bam
zcat test/tmp/ccs.fasta.fasta.gz | sed 's/ccs/0_8/g' | sed 's/\/fwd//g' | sed 's/\/rev//g' > test/tmp/ccs.fasta

-----------------
Mapping CCS reads...
-----------------
Checking test/tmp/ccs_to_ref.sam
	Running command... 
blasr test/tmp/ccs.fasta /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta --sa /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta.sa --out test/tmp/ccs_to_ref.sam --sam --noSplitSubreads  --nproc 1 
[INFO] 2023-04-22T13:57:32 [blasr] started.
[INFO] 2023-04-22T13:58:37 [blasr] ended.
-----------------
-----------------
Checking test/preprocessed/ccs_to_ref.sorted.bam.bai
	Running command... 
samtools view -Sbh test/tmp/ccs_to_ref.sam > test/tmp/ccs_to_ref.bam 
samtools sort test/tmp/ccs_to_ref.bam -o test/preprocessed/ccs_to_ref.sorted.bam > /dev/null 2>&1 
samtools index test/preprocessed/ccs_to_ref.sorted.bam
-----------------
-----------------
Checking test/tmp/snvs_candidates.vcf
	Running command... 
CONDA_BASE=$(conda info --base) 
source ${CONDA_BASE}/etc/profile.d/conda.sh 
conda activate whatshap-latest 
whatshap find_snv_candidates --sample sample /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta test/preprocessed/ccs_to_ref.sorted.bam --pacbio -o test/tmp/snvs_candidates.vcf #> /dev/null 2>&1 conda deactivate 
3 0.25
-----------------
-----------------
Checking test/variants/snvs_from_ccs.vcf
	Running command... 
CONDA_BASE=$(conda info --base) 
source ${CONDA_BASE}/etc/profile.d/conda.sh 
conda activate whatshap-latest 
whatshap genotype --sample sample --ignore-read-groups --reference /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta -o test/variants/snvs_from_ccs.vcf test/tmp/snvs_candidates.vcf test/preprocessed/ccs_to_ref.sorted.bam #> /dev/null 2>&1 conda deactivate 
This is WhatsHap (genotyping) 1.8.dev72+ge66c1a1 running under Python 3.7.16
WARNING: Read group "20cd9686" does not contain an SM field to assign it to a sample. Use --ignore-read-groups to use these alignments anyway.
[W::vcf_parse] Contig 'igh' is not defined in the header. (Quick workaround: index the file with tabix.)
Working on 1 sample from 1 family
[W::vcf_parse] Contig 'igh' is not defined in the header. (Quick workaround: index the file with tabix.)
======== Working on chromosome 'igh'
---- Initial genotyping of sample
Found 64 reads covering 14 variants
---- Processing individual sample
Using maximum coverage per sample of 15X
Found 64 reads covering 14 variants
Kept 59 reads that cover at least two variants each
Selected 36 most phase-informative reads covering 14 variants
Variants covered by at least one phase-informative read in at least one individual after read selection: 14
Genotype 1 sample by solving the genotyping problem ...
======== Writing VCF
Done writing VCF

== SUMMARY ==
Maximum memory usage: 0.095 GB
Time spent reading BAM:                         0.0 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent genotyping:                             0.1 s
Time spent writing VCF:                         0.0 s
Time spent on rest:                             0.1 s
Total elapsed time:                             0.1 s
-----------------
-----------------
Checking test/variants/snvs_phased_from_ccs.vcf
	Running command... 
CONDA_BASE=$(conda info --base) 
source ${CONDA_BASE}/etc/profile.d/conda.sh 
conda activate whatshap-latest 
whatshap phase --sample sample --reference /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta --ignore-read-groups --distrust-genotypes -o test/variants/snvs_phased_from_ccs.vcf test/variants/snvs_from_ccs.vcf test/preprocessed/ccs_to_ref.sorted.bam #> /dev/null 2>&1
conda deactivate
This is WhatsHap 1.8.dev72+ge66c1a1 running under Python 3.7.16
WARNING: Read group "20cd9686" does not contain an SM field to assign it to a sample. Use --ignore-read-groups to use these alignments anyway.
Working on 1 sample from 1 family

# Working on contig igh in individual sample
Found 10 usable heterozygous variants (0 skipped due to missing genotypes)
Found 64 reads covering 10 variants
Kept 59 reads that cover at least two variants each
Selected 36 most phase-informative reads covering 10 variants
Phasing 1 sample by solving the MEC problem ...
Largest block contains 10 variants (100.0% of accessible variants) between position 171381 and 188171

# Resource usage
Maximum memory usage: 0.052 GB
Time spent reading BAM/CRAM:                    0.0 s
Time spent parsing VCF:                         0.0 s
Time spent selecting reads:                     0.0 s
Time spent phasing:                             0.0 s
Time spent writing VCF:                         0.0 s
Time spent finding components:                  0.0 s
Time spent on rest:                             0.1 s
Total elapsed time:                             0.1 s
-----------------
-----------------
Checking test/variants/phased_blocks.txt
	Running command... 
CONDA_BASE=$(conda info --base) 
source ${CONDA_BASE}/etc/profile.d/conda.sh 
conda activate whatshap-latest 
whatshap stats --sample sample --block-list test/variants/phased_blocks.txt --chr-lengths /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/chr_lengths.txt test/variants/snvs_phased_from_ccs.vcf #> /dev/null 2>&1
conda deactivate
Found 1 sample(s) in input VCF
Read length of 28 chromosomes from /home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/chr_lengths.txt
Phasing statistics for sample sample from file test/variants/snvs_phased_from_ccs.vcf
---------------- Chromosome igh ----------------
      Variants in VCF:       14
         Heterozygous:       10    (      10    SNVs)
               Phased:       10    (      10    SNVs)
  Heterozygous phased:      100.0% (     100.0% SNVs)
             Unphased:        0    (not considered below)
           Singletons:        0    (not considered below)
               Blocks:        1

Block sizes (no. of variants)
         Sum of sizes:       10    variants
    Median block size:       10.00 variants
   Average block size:       10.00 variants
        Largest block:       10    variants
       Smallest block:       10    variants

Block lengths (basepairs)
       Sum of lengths:    16790    bp
  Median block length:    16790.00 bp
 Average block length:    16790.00 bp
        Longest block:    16790    bp
       Shortest block:    16790    bp
           Block NG50:        0    bp
-----------------
-----------------
Checking test/tmp/primary.bam.bai
	Running command... 
samtools view -Sbh -F 3884 test/alignments/ccs_to_ref_phased.sorted.bam > test/tmp/primary.bam 
samtools index test/tmp/primary.bam 
-----------------
Traceback (most recent call last):
  File "/home/msgroup/anaconda3/envs/IGv2/bin/IG", line 11, in <module>
    load_entry_point('IGenotyper==1.1', 'console_scripts', 'IG')()
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/main.py", line 35, in main
    command.main(args)
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/commands/phase.py", line 120, in main
    run_phasing(**vars(args))
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/commands/phase.py", line 114, in run_phasing
    phasing_stats(sample,files,plot_command_line,align_command_line)
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/phasing/stats.py", line 290, in phasing_stats
    stats = input_stats(files,primary_alignment_bam)
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/phasing/stats.py", line 86, in input_stats
    regions_covered = target_region_coverage(files,primary_alignment_bam)
  File "/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/phasing/stats.py", line 30, in target_region_coverage
    for pileupcolumn in sam.pileup(chrom,start,end):
  File "pysam/libcalignmentfile.pyx", line 1326, in pysam.libcalignmentfile.AlignmentFile.pileup
  File "pysam/libchtslib.pyx", line 685, in pysam.libchtslib.HTSFile.parse_region
ValueError: invalid contig `ighc`

**Comment by Xiujia-Yang** [comment]
The absence of the `ighc` record in the reference sequences `/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/reference.fasta` should be responsible for this issue. Thus, it can be solved by deleting the record of `ighc` in the bed file `/home/msgroup/anaconda3/envs/IGv2/lib/python2.7/site-packages/IGenotyper-1.1-py2.7.egg/IGenotyper/data/target_region.bed`.

**Comment by veredkl** [comment]
I have the above error, so I delete the record of ighc in the bed file but new I get different error.

Checking test111/plots/phasing.png
        Running command...
CONDA_BASE=$(conda info --base)
source ${CONDA_BASE}/etc/profile.d/conda.sh
conda activate pygenometracks
pyGenomeTracks --tracks test111/tmp/pygenometracks.ini --region igh:1-1193129 -o test111/plots/phasing.png
Traceback (most recent call last):
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 577, in check_file_exists
    open(file_name_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: 'test111/tmp/hap0.bw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 585, in check_file_exists
    open(name_with_tracks_path_to_check, 'r').close()
FileNotFoundError: [Errno 2] No such file or directory: 'test111/tmp/test111/tmp/hap0.bw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/veredk/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in <module>
    main(args)
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/plotTracks.py", line 321, in main
    plot_regions=regions, plot_width=args.plotWidth)
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 78, in __init__
    self.parse_tracks(tracks_file, plot_regions=plot_regions)
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 512, in parse_tracks
    track_options['file_type'] == 'hic_matrix')
  File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 588, in check_file_exists
    raise InputError(f"File in section [{track_dict['section_name']}] "
pygenometracks.utilities.InputError: File in section [8. [hap 0 bw]] not found:
test111/tmp/hap0.bw


[output.txt](https://github.com/oscarlr/IGenotyper/files/12426256/output.txt)

**Comment by Xiujia-Yang** [comment]
> I have the above error, so I delete the record of ighc in the bed file but new I get different error. I run it on your example file.
> 
> Checking test111/plots/phasing.png Running command... CONDA_BASE=$(conda info --base) source ${CONDA_BASE}/etc/profile.d/conda.sh conda activate pygenometracks pyGenomeTracks --tracks test111/tmp/pygenometracks.ini --region igh:1-1193129 -o test111/plots/phasing.png Traceback (most recent call last): File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 577, in check_file_exists open(file_name_to_check, 'r').close() FileNotFoundError: [Errno 2] No such file or directory: 'test111/tmp/hap0.bw'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 585, in check_file_exists open(name_with_tracks_path_to_check, 'r').close() FileNotFoundError: [Errno 2] No such file or directory: 'test111/tmp/test111/tmp/hap0.bw'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/user/veredk/.conda/envs/pygenometracks/bin/pyGenomeTracks", line 11, in main(args) File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/plotTracks.py", line 321, in main plot_regions=regions, plot_width=args.plotWidth) File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 78, in **init** self.parse_tracks(tracks_file, plot_regions=plot_regions) File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 512, in parse_tracks track_options['file_type'] == 'hic_matrix') File "/home/user/veredk/.conda/envs/pygenometracks/lib/python3.7/site-packages/pygenometracks/tracksClass.py", line 588, in check_file_exists raise InputError(f"File in section [{track_dict['section_name']}] " pygenometracks.utilities.InputError: File in section [8. [hap 0 bw]] not found: test111/tmp/hap0.bw
> 
> [output.txt](https://github.com/oscarlr/IGenotyper/files/12426256/output.txt)

This error can be ignored as the tutorial indicates (code block under `Testing IGenotyper installation`). This is because `hap0.bw` is a file storing the coverage statistics for unphased reads. This file is missing because of the absence of unphased reads curated in `0.bam`. `hap0.bw` is used to visualize the coverage details for unphased reads, a step having no influence on the subsequent `assembly` utility.
